import { readFileSync, writeFileSync } from 'fs'

const es = JSON.parse(readFileSync('src/messages/es.json', 'utf-8'))
const en = JSON.parse(readFileSync('src/messages/en.json', 'utf-8'))

const landing = {
  es: {
    nav_features: "Funciones",
    nav_howItWorks: "Cómo funciona",
    nav_pricing: "Precios",
    nav_login: "Iniciar Sesión",
    nav_cta: "Empezar Gratis",
    hero_badge: "CRM para WhatsApp Business",
    hero_title: "Gestiona tu negocio por WhatsApp desde un solo lugar",
    hero_subtitle: "Bandeja de entrada compartida, contactos, pipelines de ventas, broadcasts y automatizaciones. Todo lo que necesitas para escalar tu negocio por WhatsApp.",
    hero_cta: "Empezar Gratis",
    hero_ctaSecondary: "Ver Planes",
    hero_trial: "14 días de prueba • No se requiere tarjeta de crédito",
    features_title: "Todo lo que necesitas",
    features_subtitle: "Una herramienta integral para tu negocio por WhatsApp. Sin necesidad de combinar múltiples aplicaciones.",
    features_card_0_title: "Bandeja de Entrada Compartida",
    features_card_0_desc: "Todo tu equipo trabaja desde un mismo inbox. Asigna conversaciones, responde como equipo y nunca pierdas un lead.",
    features_card_1_title: "Centro de Contactos",
    features_card_1_desc: "Etiquetas, campos personalizados, notas y deduplicación automática. Importa contactos desde CSV.",
    features_card_2_title: "Pipeline de Ventas",
    features_card_2_desc: "Arrastra tratos por etapas. Ve qué está ganado, qué se está cayendo y dónde está atascado el revenue.",
    features_card_3_title: "Campañas Broadcast",
    features_card_3_desc: "Envía plantillas aprobadas por Meta a listas segmentadas. Tracking en tiempo real de entrega y lecturas.",
    features_card_4_title: "Automatizaciones",
    features_card_4_desc: "Bienvenida a nuevos contactos, sigue-up automáticos, routing por keywords. Constructor visual de flujos.",
    features_card_5_title: "Asistente de IA",
    features_card_5_desc: "Genera respuestas con IA. Trae tu propia API key de OpenAI o Anthropic. Sin costo adicional por mensaje.",
    howItWorks_title: "En vivo en menos de 30 minutos",
    howItWorks_subtitle: "La mayoría de equipos están operativos antes de terminar su primer café.",
    howItWorks_step_0_title: "Conecta tu número de WhatsApp",
    howItWorks_step_0_desc: "Pega tu phone number ID y access token desde Meta. Funciona con cualquier proveedor de WhatsApp Business API.",
    howItWorks_step_1_title: "Trae tus contactos",
    howItWorks_step_1_desc: "Importa un CSV o deja que los mensajes entrantes construyan tu lista automáticamente.",
    howItWorks_step_2_title: "Responde, automatiza y mide",
    howItWorks_step_2_desc: "Usa la bandeja compartida, configura flujos para trabajo repetitivo y haz seguimiento de lo que funciona.",
    pricing_title: "Planes diseñados para ti",
    pricing_subtitle: "Elige el plan que mejor se adapte a tu negocio. Todos incluyen soporte técnico y actualizaciones.",
    pricing_plan_0_name: "Gratis",
    pricing_plan_0_price: "RD$0",
    pricing_plan_0_desc: "Para probar",
    pricing_plan_0_feature_0: "25 contactos",
    pricing_plan_0_feature_1: "1 miembro del equipo",
    pricing_plan_0_feature_2: "Solo bandeja de entrada",
    pricing_plan_0_feature_3: "Sin broadcasts",
    pricing_plan_0_feature_4: "Sin automatizaciones",
    pricing_plan_0_feature_5: "Sin WhatsApp",
    pricing_plan_0_cta: "Empezar Gratis",
    pricing_plan_1_name: "Básico",
    pricing_plan_1_price: "RD$1,500",
    pricing_plan_1_desc: "Para pequeños negocios",
    pricing_plan_1_feature_0: "500 contactos",
    pricing_plan_1_feature_1: "3 miembros del equipo",
    pricing_plan_1_feature_2: "Broadcasts ilimitados",
    pricing_plan_1_feature_3: "Sin automatizaciones",
    pricing_plan_1_feature_4: "1 número de WhatsApp",
    pricing_plan_1_cta: "Comenzar Trial",
    pricing_plan_2_name: "Pro",
    pricing_plan_2_price: "RD$3,000",
    pricing_plan_2_desc: "Para equipos en crecimiento",
    pricing_plan_2_feature_0: "2,000 contactos",
    pricing_plan_2_feature_1: "10 miembros del equipo",
    pricing_plan_2_feature_2: "Broadcasts ilimitados",
    pricing_plan_2_feature_3: "Automatizaciones",
    pricing_plan_2_feature_4: "Flujos visuales",
    pricing_plan_2_feature_5: "3 números de WhatsApp",
    pricing_plan_2_cta: "Comenzar Trial",
    pricing_plan_3_name: "Empresarial",
    pricing_plan_3_price: "RD$6,000",
    pricing_plan_3_desc: "Para empresas",
    pricing_plan_3_feature_0: "Contactos ilimitados",
    pricing_plan_3_feature_1: "Miembros ilimitados",
    pricing_plan_3_feature_2: "Todo incluido",
    pricing_plan_3_feature_3: "Acceso API",
    pricing_plan_3_feature_4: "Números ilimitados",
    pricing_plan_3_feature_5: "Soporte prioritario",
    pricing_plan_3_cta: "Contactar Ventas",
    pricing_help: "¿Necesitas ayuda para elegir?",
    pricing_contact: "Contáctanos",
    why_title: "¿Por qué Zynex CRM?",
    why_item_0_title: "Datos seguros",
    why_item_0_desc: "Tu información almacenada de forma segura. Respaldo diario y encriptación.",
    why_item_1_title: "Soporte en español",
    why_item_1_desc: "Equipo de soporte disponible para ayudarte en lo que necesites.",
    why_item_2_title: "Pensado para Latam",
    why_item_2_desc: "Precios en pesos dominicanos, integración con WhatsApp Business API oficial.",
    why_item_3_title: "Actualizaciones constantes",
    why_item_3_desc: "Nuevas funciones regularmente basadas en feedback de usuarios.",
    why_testimonial: "La mejor herramienta para gestionar WhatsApp para mi negocio. Fácil de usar y el soporte es excelente.",
    why_author: "- Carlos M., Emprendedor",
    faq_title: "Preguntas Frecuentes",
    faq_item_0_q: "¿Zynex CRM es gratuito?",
    faq_item_0_a: "Tenemos un plan gratuito para siempre con 50 contactos y 1 miembro. También ofrecemos 14 días de prueba de todos los planes pagos.",
    faq_item_1_q: "¿Funciona con WhatsApp oficial?",
    faq_item_1_a: "Sí, Zynex CRM funciona con la API oficial de WhatsApp Business de Meta. Solo necesitas tu phone number ID y access token.",
    faq_item_2_q: "¿Puedo enviar mensajes masivos?",
    faq_item_2_a: "Sí, los planes Básico, Pro y Empresarial incluyen broadcasts ilimitados con plantillas aprobadas por Meta.",
    faq_item_3_q: "¿Cómo funciona el pago?",
    faq_item_3_a: "Aceptamos transferencias bancarias. Cuando solicitas un plan, te damos los datos para realizar el pago y tu cuenta se activa manualmente.",
    faq_item_4_q: "¿Mis datos están seguros?",
    faq_item_4_a: "Sí, tus datos están almacenados de forma segura con respaldos diarios y encriptación. Puedes exportar tu información cuando lo necesites.",
    faq_item_5_q: "¿Necesito saber programar?",
    faq_item_5_a: "No, Zynex CRM está diseñado para que cualquier persona pueda usarlo. La interfaz es intuitiva y no requiere conocimientos técnicos.",
    cta_title: "¿Listo para empezar?",
    cta_subtitle: "Crea tu cuenta gratis y descubre cómo Zynex CRM puede ayudarte a hacer crecer tu negocio.",
    cta_button: "Crear Cuenta Gratis",
    cta_footer: "No se requiere tarjeta de crédito • 14 días de prueba",
    footer_product: "Producto",
    footer_company: "Empresa",
    footer_support: "Soporte",
    footer_docs: "Documentación",
    footer_copyright: "© 2024 Zynex SRL. Todos los derechos reservados.",
    footer_powered: "Construido sobre WhatsApp Business API • Meta",
  },
  en: {
    nav_features: "Features",
    nav_howItWorks: "How it works",
    nav_pricing: "Pricing",
    nav_login: "Sign In",
    nav_cta: "Get Started Free",
    hero_badge: "WhatsApp Business CRM",
    hero_title: "Manage your WhatsApp business from one place",
    hero_subtitle: "Shared inbox, contacts, sales pipelines, broadcasts and automations. Everything you need to scale your WhatsApp business.",
    hero_cta: "Get Started Free",
    hero_ctaSecondary: "View Plans",
    hero_trial: "14-day trial • No credit card required",
    features_title: "Everything you need",
    features_subtitle: "An all-in-one tool for your WhatsApp business. No need to combine multiple apps.",
    features_card_0_title: "Shared Inbox",
    features_card_0_desc: "Your whole team works from the same inbox. Assign conversations, reply as a team and never miss a lead.",
    features_card_1_title: "Contact Center",
    features_card_1_desc: "Tags, custom fields, notes and automatic deduplication. Import contacts from CSV.",
    features_card_2_title: "Sales Pipeline",
    features_card_2_desc: "Drag deals through stages. See what's won, what's falling through and where revenue is stuck.",
    features_card_3_title: "Broadcast Campaigns",
    features_card_3_desc: "Send Meta-approved templates to segmented lists. Real-time tracking of delivery and reads.",
    features_card_4_title: "Automations",
    features_card_4_desc: "Welcome new contacts, automatic follow-ups, keyword routing. Visual flow builder.",
    features_card_5_title: "AI Assistant",
    features_card_5_desc: "Generate responses with AI. Bring your own OpenAI or Anthropic API key. No additional cost per message.",
    howItWorks_title: "Live in under 30 minutes",
    howItWorks_subtitle: "Most teams are up and running before finishing their first coffee.",
    howItWorks_step_0_title: "Connect your WhatsApp number",
    howItWorks_step_0_desc: "Paste your phone number ID and access token from Meta. Works with any WhatsApp Business API provider.",
    howItWorks_step_1_title: "Bring your contacts",
    howItWorks_step_1_desc: "Import a CSV or let incoming messages build your list automatically.",
    howItWorks_step_2_title: "Reply, automate and measure",
    howItWorks_step_2_desc: "Use the shared inbox, set up flows for repetitive work and track what works.",
    pricing_title: "Plans designed for you",
    pricing_subtitle: "Choose the plan that best fits your business. All include technical support and updates.",
    pricing_plan_0_name: "Free",
    pricing_plan_0_price: "RD$0",
    pricing_plan_0_desc: "To try out",
    pricing_plan_0_feature_0: "25 contacts",
    pricing_plan_0_feature_1: "1 team member",
    pricing_plan_0_feature_2: "Inbox only",
    pricing_plan_0_feature_3: "No broadcasts",
    pricing_plan_0_feature_4: "No automations",
    pricing_plan_0_feature_5: "No WhatsApp",
    pricing_plan_0_cta: "Get Started Free",
    pricing_plan_1_name: "Basic",
    pricing_plan_1_price: "RD$1,500",
    pricing_plan_1_desc: "For small businesses",
    pricing_plan_1_feature_0: "500 contacts",
    pricing_plan_1_feature_1: "3 team members",
    pricing_plan_1_feature_2: "Unlimited broadcasts",
    pricing_plan_1_feature_3: "No automations",
    pricing_plan_1_feature_4: "1 WhatsApp number",
    pricing_plan_1_cta: "Start Trial",
    pricing_plan_2_name: "Pro",
    pricing_plan_2_price: "RD$3,000",
    pricing_plan_2_desc: "For growing teams",
    pricing_plan_2_feature_0: "2,000 contacts",
    pricing_plan_2_feature_1: "10 team members",
    pricing_plan_2_feature_2: "Unlimited broadcasts",
    pricing_plan_2_feature_3: "Automations",
    pricing_plan_2_feature_4: "Visual flows",
    pricing_plan_2_feature_5: "3 WhatsApp numbers",
    pricing_plan_2_cta: "Start Trial",
    pricing_plan_3_name: "Enterprise",
    pricing_plan_3_price: "RD$6,000",
    pricing_plan_3_desc: "For companies",
    pricing_plan_3_feature_0: "Unlimited contacts",
    pricing_plan_3_feature_1: "Unlimited members",
    pricing_plan_3_feature_2: "Everything included",
    pricing_plan_3_feature_3: "API access",
    pricing_plan_3_feature_4: "Unlimited numbers",
    pricing_plan_3_feature_5: "Priority support",
    pricing_plan_3_cta: "Contact Sales",
    pricing_help: "Need help choosing?",
    pricing_contact: "Contact us",
    why_title: "Why Zynex CRM?",
    why_item_0_title: "Secure data",
    why_item_0_desc: "Your information stored securely. Daily backups and encryption.",
    why_item_1_title: "Spanish support",
    why_item_1_desc: "Support team available to help you with anything you need.",
    why_item_2_title: "Made for Latam",
    why_item_2_desc: "Prices in Dominican pesos, official WhatsApp Business API integration.",
    why_item_3_title: "Constant updates",
    why_item_3_desc: "New features regularly based on user feedback.",
    why_testimonial: "The best tool to manage WhatsApp for my business. Easy to use and the support is excellent.",
    why_author: "- Carlos M., Entrepreneur",
    faq_title: "Frequently Asked Questions",
    faq_item_0_q: "Is Zynex CRM free?",
    faq_item_0_a: "We have a forever-free plan with 50 contacts and 1 member. We also offer 14-day trials of all paid plans.",
    faq_item_1_q: "Does it work with official WhatsApp?",
    faq_item_1_a: "Yes, Zynex CRM works with Meta's official WhatsApp Business API. You just need your phone number ID and access token.",
    faq_item_2_q: "Can I send bulk messages?",
    faq_item_2_a: "Yes, Basic, Pro and Enterprise plans include unlimited broadcasts with Meta-approved templates.",
    faq_item_3_q: "How does payment work?",
    faq_item_3_a: "We accept bank transfers. When you request a plan, we give you the details to make the payment and your account is activated manually.",
    faq_item_4_q: "Is my data safe?",
    faq_item_4_a: "Yes, your data is stored securely with daily backups and encryption. You can export your information whenever you need.",
    faq_item_5_q: "Do I need to know how to code?",
    faq_item_5_a: "No, Zynex CRM is designed for anyone to use. The interface is intuitive and requires no technical knowledge.",
    cta_title: "Ready to get started?",
    cta_subtitle: "Create a free account and discover how Zynex CRM can help you grow your business.",
    cta_button: "Create Free Account",
    cta_footer: "No credit card required • 14-day trial",
    footer_product: "Product",
    footer_company: "Company",
    footer_support: "Support",
    footer_docs: "Documentation",
    footer_copyright: "© 2024 Zynex SRL. All rights reserved.",
    footer_powered: "Built on WhatsApp Business API • Meta",
  }
}

let esCount = 0, enCount = 0
for (const [key, value] of Object.entries(landing.es)) {
  if (!(key in es)) {
    es[key] = value
    esCount++
  }
}
for (const [key, value] of Object.entries(landing.en)) {
  if (!(key in en)) {
    en[key] = value
    enCount++
  }
}

// Sort
const esSorted = Object.keys(es).sort().reduce((a, k) => { a[k] = es[k]; return a }, {})
const enSorted = Object.keys(en).sort().reduce((a, k) => { a[k] = en[k]; return a }, {})

writeFileSync('src/messages/es.json', JSON.stringify(esSorted, null, 2) + '\n')
writeFileSync('src/messages/en.json', JSON.stringify(enSorted, null, 2) + '\n')

console.log(`es.json: +${esCount} keys (now ${Object.keys(esSorted).length})`)
console.log(`en.json: +${enCount} keys (now ${Object.keys(enSorted).length})`)
